import pyautogui
import time
import os
import random

os.popen('start firefox')
time.sleep(1)
pyautogui.write('https://www.tribalwars.net/en-dk/')
pyautogui.press('enter')
time.sleep(3)
coord = pyautogui.locateCenterOnScreen(r'.\assets\world.png',confidence=0.85)
pyautogui.moveTo(coord,duration=1)
time.sleep(1)
pyautogui.leftClick(coord)
time.sleep(3)
coord = pyautogui.locateCenterOnScreen(r'.\assets\ic_mey.png',confidence=0.85)
pyautogui.moveTo(coord,duration=1)
time.sleep(1)
pyautogui.leftClick(coord)
time.sleep(2)
coord = pyautogui.locateCenterOnScreen(r'.\assets\temizlik.png',confidence=0.85)
pyautogui.moveTo(coord,duration=1)
time.sleep(1)
pyautogui.leftClick(coord)
time.sleep(2)
pyautogui.press('space')
time.sleep(1)
mizrak_coord = pyautogui.locateCenterOnScreen(r'.\assets\mizrak.png',confidence=0.85)
kilic_coord = pyautogui.locateCenterOnScreen(r'.\assets\kilic.png',confidence=0.85)
#print(mizrak_coord,kilic_coord)
print(mizrak_coord.x)
pyautogui.moveTo((mizrak_coord.x,mizrak_coord.y+30))
pyautogui.leftClick()
time.sleep(1)
pyautogui.write('11')
pyautogui.moveTo((kilic_coord.x,kilic_coord.y+30))
pyautogui.leftClick()
time.sleep(1)
pyautogui.write('10')
basla_coord = pyautogui.locateCenterOnScreen(r'.\assets\basla.png',confidence=0.85)
pyautogui.moveTo(basla_coord,duration=1)
pyautogui.leftClick()
coord = (1890,20)
time.sleep(1)
pyautogui.moveTo(coord)
time.sleep(1)
pyautogui.leftClick()
